import type { TableConfig } from "../services/tableCrud.js";

export const tableConfigs = {
  articles: {
    table: "articles",
    columns: [
      "type",
      "title",
      "slug",
      "description",
      "content",
      "category",
      "tags",
      "featured_image",
      "gallery_images",
      "pdf_url",
      "author",
      "publish_date",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "publish_date DESC, created_at DESC",
  },
  topics: {
    table: "topics",
    columns: [
      "type",
      "title",
      "slug",
      "description",
      "icon",
      "article_count",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "title ASC",
  },
  books: {
    table: "books",
    columns: [
      "type",
      "title",
      "slug",
      "description",
      "author",
      "cover_image",
      "buy_link",
      "publication_date",
      "publisher",
      "isbn",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "publication_date DESC",
  },
  podcasts: {
    table: "podcasts",
    columns: [
      "type",
      "title",
      "slug",
      "summary",
      "description",
      "audio_url",
      "video_url",
      "duration",
      "episode_number",
      "platform_links",
      "guest_name",
      "cover_image",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "episode_number DESC",
  },
  about: {
    table: "about",
    columns: ["type", "title", "slug", "description", "content", "status"],
    publicWhere: "status = 'published'",
    orderBy: "updated_at DESC",
  },
  practiceAreas: {
    table: "practice_areas",
    columns: [
      "slug",
      "title",
      "description",
      "icon",
      "card_number",
      "sub_tags",
      "sort_order",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  timelineEntries: {
    table: "timeline_entries",
    columns: ["section", "year_label", "title", "subtitle", "sort_order", "status"],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  memberships: {
    table: "memberships",
    columns: ["name", "subtitle", "icon", "sort_order", "status"],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  speakingEvents: {
    table: "speaking_events",
    columns: [
      "event_date",
      "month_label",
      "day_label",
      "event_type",
      "title",
      "venue",
      "sort_order",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC, event_date ASC",
  },
  collaborationServices: {
    table: "collaboration_services",
    columns: ["title", "description", "icon", "cta_label", "cta_target", "sort_order", "status"],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  resources: {
    table: "resources",
    columns: [
      "slug",
      "title",
      "description",
      "resource_type",
      "icon",
      "file_url",
      "sort_order",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  testimonials: {
    table: "testimonials",
    columns: [
      "quote",
      "author_initials",
      "author_name",
      "author_role",
      "rating",
      "sort_order",
      "status",
    ],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  tickerItems: {
    table: "ticker_items",
    columns: ["label", "highlight_text", "sort_order", "is_active"],
    publicWhere: "is_active = 1",
    orderBy: "sort_order ASC",
  },
  publicationLogos: {
    table: "publication_logos",
    columns: ["name", "url", "logo_url", "sort_order", "is_active"],
    publicWhere: "is_active = 1",
    orderBy: "sort_order ASC",
  },
  contactDetails: {
    table: "contact_details",
    columns: ["icon", "label", "value", "link_url", "sort_order", "status"],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
  socialLinks: {
    table: "social_links",
    columns: ["platform", "label", "url", "sort_order", "status"],
    publicWhere: "status = 'published'",
    orderBy: "sort_order ASC",
  },
} satisfies Record<string, TableConfig>;
